### ISSUE TITLE
Can this situation be achieved?

### ISSUE THREAD

**Issue by giantss** [ayushinigam/react-native-custom-radio-group#3]
Thanks very much to the open source plug-in provided by the author, but I have a problem in the use process and I don't know how to solve it.
## ideal:
![image](https://user-images.githubusercontent.com/13778798/37706758-9c124ba4-2d3b-11e8-92c9-2e7168c809c9.png)

## reality:
![image](https://user-images.githubusercontent.com/13778798/37706162-76e45b9e-2d39-11e8-977a-2f5760103148.png)

code:
```
<RadioGroup
                    radioGroupList={radioGroupList}
                    initialValue = {'10'}


                    buttonContainerStyle = {{flex:1,margin: 10, borderWidth: 1, borderColor: Color.whiteE}}
                    buttonContainerActiveStyle = {{backgroundColor: Color.yellowFCE}}
                    onChange={(value) => this._selectMoney(value) }
                    ref={e => this.RadioGroup1 = e}
                />

                <RadioGroup
                    radioGroupList={radioGroupList2}
                    buttonContainerStyle = {{flex:1,margin: 10, borderWidth: 0}}
                    buttonContainerActiveStyle = {{backgroundColor: Color.yellowFCE}}
                    onChange={(value) => this._selectMoney(value) }
                    ref={e => this.RadioGroup2 = e}

                />
```
I want to implement the button in the first row or the second row of buttons to return the row of buttons to the initial state. What should I do? help me.

**Comment by giantss** [comment]
@ayushinigam

**Comment by giantss** [comment]
@ayushinigam Do you plan to maintain such a project?

**Comment by ayushinigam** [comment]
@giantss My apologies for the delay in response 
To your question: **Yes, aligning the radio buttons in multiple lines can be achieved by styling**. The component accepts styling props for the same.
Although, there is no particular prop for spreading the button across multiple lines. This would be an enhancement, I am slightly busy these days but will release an updated version which the enhancement. 
Feel free to raise a PR if you need it urgently. 🙂

Here's an example of solving this through styling:
```javascript
<View style={{width: 250, marginHorizontal: 50}}>
        <Text> SELECT: </Text>
        <RadioGroup radioGroupList={radioGroupList} containerStyle={{flexWrap: 'wrap'}} buttonContainerStyle={{marginTop: 10}}/>
</View>
```


Output: 
<img width="307" alt="screen shot 2018-04-01 at 11 14 44 pm" src="https://user-images.githubusercontent.com/16535047/38176011-555ed02a-3604-11e8-9826-c5b25d7008df.png">

**Comment by giantss** [comment]
@ayushinigam Thank you for your answer, this has to do to solve the problem of auto-wrap, but I do not know why when I select a certain option, ios phone memory will continue to soar until it crashes.I feel this is a more serious bug,You can test it.
The following figure is a monitor.
![image](https://user-images.githubusercontent.com/13778798/38179894-c49eb15c-365a-11e8-89bd-23eec44a3aec.png)

**Comment by ayushinigam** [comment]
@giantss I am using the component in a complex application and the memory usage doesn't shoot up on selecting a button. 
Here's the memory analysis graph: 
<img width="880" alt="screen shot 2018-04-03 at 10 43 10 pm" src="https://user-images.githubusercontent.com/16535047/38264875-f8614ca6-3791-11e8-8282-8dc606e53338.png">

Please review your implementation as there seems to be no instance of memory leak in the component :)

**Comment by giantss** [comment]
Did you use `containerStyle={{flexWrap: 'wrap'}}`when testing? This will not happen if you do not use,Whether it is a real machine or a simulator.This situation does not happen every time, but the odds are very large. How many times have you tried it? I'm pretty sure that the skyrocketing memory must be related to `RadioGroup`. I don't know if I'm using the wrong code or if the component is already having this problem.

This is the code
```
const radioGroupList = [{
            label: '10元',
            value: '10'
        }, {
            label: '30元',
            value: '30'
        }, {
            label: '50元',
            value: '50'
        },{
            label: '100元',
            value: '100'
        }, {
            label: '200元',
            value: '200'
        }, {
            label: '其他金额',
            value: '其他金额'
        }];

```

```
 <RadioGroup
                    radioGroupList={radioGroupList}
                    initialValue = {'10'}
                    containerStyle={{flexWrap: 'wrap'}}
                    buttonContainerStyle = {{width: this._getButtonWidth(), margin: 10, borderWidth: 1, borderColor: Color.whiteE}}
                    buttonContainerActiveStyle = {{backgroundColor: Color.yellow}}
                    onChange={(value) => this._selectMoney(value) }
                    ref={e => this.RadioGroup = e}
                />
```
@ayushinigam

**Comment by ayushinigam** [comment]
@giantss yes, I had used `containerStyle={{flexWrap: 'wrap'}}` as mentioned in the snippet above. 
The `containerStyle` provides the flexibility of passing custom styles.

Regarding the memory leak issue,
To your question: I am using the component in a production app and haven't faced the issue yet. 
This is a simple view based component with a local state without any major external dependencies, which reduces the chances of such scenarios.

**If you are able to replicate and fix the issue. Please raise a PR** ✌️
