### ISSUE TITLE
is it possible to set the index or radio option programmatically ?

### ISSUE THREAD

**Issue by dongawli** [ayushinigam/react-native-custom-radio-group#4]
Hi, 

Thank you for the simple and useful radio group component. 

Is it possible to set the index or radio option programmatically? 

Regards,
-Vijay

**Comment by ayushinigam** [comment]
@dongawli Sorry, didn't understand your query.
It will be great if you can explain the use case here :)

**Comment by dongawli** [comment]
@ayushinigam : Here is the use case. 
I've drawer menu where user needs to select the profile type (myself, son, daughter, brother, sister etc). After selecting the profile type, the gender (male/female) needs to be auto selected which I've created using react-native-custom-radio-group component. 
Is there anyway I can select Male / Female or set the index of radio group?
Like there is initialValue property, is there any such property to set the index or any function by which we set the index?
![image](https://user-images.githubusercontent.com/19324345/39738644-f3c86da4-52a9-11e8-9683-5ebdb8faca58.png)

**Comment by dongawli** [comment]
Any update here?

**Comment by dongawli** [comment]
Fixed the issue by calling .radioSelect(key, value) method. 

Thank you.

**Comment by ayushinigam** [comment]
@dongawli Glad you worked it out! 😎
Had been travelling lately, hence the delay in response.

Closing the issue now ✌️
